/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:93a04c49-0ce5-4f50-b955-b847f8315cf0",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_HEfFAW2ZF",
    "aws_user_pools_web_client_id": "6ijdrgg2afsbqkacbn5a3g1qun",
    "oauth": {}
};


export default awsmobile;
