/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:db1f4bac-e01c-4e8c-a19c-9f14e065534e",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_2HOwknFzP",
    "aws_user_pools_web_client_id": "30gr5q5k5epbu15cipgomcnl6g",
    "oauth": {}
};


export default awsmobile;
